version: "3"

services:
  api:
    image: golang:1.14.1-buster
    tty: true
    environment:
      PORT: 8080
      GITHUB_APP_ID: 0
      GITHUB_WEBHOOK_SECRET: aiueo
      GITHUB_ENTERPRISE_URL: ""
      GITHUB_ENTERPRISE_UPLOAD_URL: ""
      GITHUB_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - 8080:8080

  expose:
    image: wernight/ngrok:latest
    command: ngrok http api:8080
    ports:
      - 4040:4040
